name: Sync Google Docs to Website

on:
  schedule:
    - cron: '0 0 1,15 * *'  # Runs at midnight UTC on the 1st and 15th of every month
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Create credentials file
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

      - name: Fetch and update from Google Docs
        run: |
          python fetch_doc.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.html
          git commit -m "Auto-update resume from Google Docs - $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
